.\"	$OpenBSD$
.\"
.\" Copyright (c) 2024 genua GmbH <bluhm@genua.de>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt PFRESOLVECTL 8
.Os
.Sh NAME
.Nm pfresolvectl
.Nd control the pfresolved daemon
.Sh SYNOPSIS
.Nm
.Op Fl s Ar socket
.Ar command
.Op Ar arg ...
.Sh DESCRIPTION
The
.Nm
program can be used to control the
.Xr pfresolved 8
daemon.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl s Ar socket
The control socket used to communicate with
.Xr pfresolved 8 .
The default is
.Pa /var/run/pfresolved.sock .
.El
.Sh PFRESOLVED CONTROL COMMANDS
The following commands are available to control
.Xr pfresolved 8 :
.Bl -tag -width Ds
.It Cm log Ar level
Set the loglevel to the specified value.
Possible levels are:
.Cm warn ,
.Cm notice ,
.Cm info ,
and
.Cm debug .
.It Cm reload
Reload the configuration from the current configuration file.
.It Cm hints
Write the latest resolve results into the configured hints file.
.El
.Sh SEE ALSO
.Xr pfresolved 8
.Sh AUTHORS
.An Carsten Beckmann
